<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>

    <div class="wrapper col6">
		<div id="copyright">
			<p class="fl_left">
				Copyright &copy; 2013 - All Rights Reserved - <a href="#">Java41</a>
			</p>
			<p class="fl_right">
				Generated by <a href="http://www.bitacademy.com/"
					title="Free Website Templates">BIT java41</a>
			</p>
			<br class="clear" />
		</div>
	</div>